import assert from 'node:assert/strict'
import test from 'node:test'

import { IPC, type IpcEventChannel, type IpcInvokeChannel, type IpcSyncChannel } from './ipc-channels.js'

function leafValues(value: unknown): string[] {
  if (typeof value === 'string') return [value]
  if (value && typeof value === 'object') {
    return Object.values(value as Record<string, unknown>).flatMap(leafValues)
  }
  return []
}

test('IPC invoke constants cover the typed invoke registry', () => {
  const channels = new Set(leafValues(IPC.invoke))
  const typed: IpcInvokeChannel[] = [
    'window:minimize',
    'window:moveBy',
    'window:maximize',
    'window:close',
    'window:toggleFullscreen',
    'window:toggleDevTools',
    'window:desktopWallpaper',
    'wallpapers:list',
    'wallpapers:add',
    'wallpapers:read',
    'wallpapers:remove',
    'profiles:switchTo',
    'profiles:remove',
    'windows:context',
    'windows:list',
    'windows:detachTabs',
    'windows:returnTabs',
    'windows:revealTab',
    'windows:showBrowser',
    'windows:capture',
    'windows:reportDockSurface',
    'windows:routeCrossDock',
    'windows:completeCrossDock',
    'tools:setEnabledMany',
    'browser:setBounds',
    'browser:navigate',
    'browser:back',
    'browser:forward',
    'browser:reload',
    'browser:searchHistory',
    'browser:removeHistory',
    'browser:suggest',
    'browser:snapshot',
    'browser:newTab',
    'browser:newTabToRight',
    'browser:openTab',
    'browser:closeTab',
    'browser:closeOtherTabs',
    'browser:closeTabsToRight',
    'browser:duplicateTab',
    'browser:reloadTab',
    'browser:renameTab',
    'browser:selectTab',
    'browser:capture',
    'browser:openVideoHub',
    'browser:videoCompare',
    'browser:resolvePermission',
    'browserDownloads:list',
    'browserDownloads:pause',
    'browserDownloads:resume',
    'browserDownloads:cancel',
    'browserDownloads:reveal',
    'browserDownloads:clear',
    'localFiles:listDirectory',
    'localFiles:open',
    'localFiles:preview',
    'localFiles:readPreview',
    'localFiles:revealPath',
    'localFiles:openImage',
    'localFiles:image',
    'localFiles:revealImage',
    'localFiles:video',
    'localFiles:revealVideo',
    'localFiles:file',
    'localFiles:revealFile',
    'localFiles:setView',
    'localFiles:searchVideos',
    'localFiles:videoRecents',
    'localFiles:pickVideo',
    'savedSites:list',
    'savedSites:save',
    'savedSites:update',
    'savedSites:remove',
    'notes:list',
    'notes:read',
    'notes:create',
    'notes:save',
    'notes:rename',
    'notes:remove',
    'notes:bind',
    'notes:unbind',
    'agentRuns:list',
    'agentRuns:start',
    'agentRuns:pause',
    'agentRuns:resume',
    'agentRuns:stop',
    'agentLibrary:list',
    'agentLibrary:save',
    'agentLibrary:update',
    'agentLibrary:remove',
    'agentLibrary:optimize',
    'agentLibrary:cancelOptimize',
    'chat:snapshot',
    'chat:historyPage',
    'chat:send',
    'chat:interrupt',
    'chat:selectPane',
    'chat:setVisiblePanes',
    'chat:selectModel',
    'chat:selectReasoningEffort',
    'chat:readProviderUsage',
    'chat:refreshPlanUsage',
    'chat:login',
    'chat:listChats',
    'chat:newPeer',
    'chat:closePeer',
    'chat:continueInNewPeer',
    'chat:openChat',
    'chat:archiveChat',
    'chat:unarchiveChat',
    'chat:setChatPinned',
    'chat:renameChat',
    'chat:retryChatTitle',
    'chat:compactConversation',
    'chat:chooseProject',
    'chat:selectProject',
    'chat:clearProject',
    'chat:selectSpace',
    'chat:providerAvailability',
    'chat:providerOnboarding',
    'chat:providerSignIn',
    'credentials:status',
    'credentials:list',
    'credentials:save',
    'credentials:reveal',
    'credentials:remove',
    'credentials:rename',
    'credentials:setAgentAccess',
    'security:get',
    'security:set',
    'security:importCookies',
    'security:resolveCredentialApproval',
    'tools:manifest',
    'tools:telemetry',
    'tools:clearTelemetry',
    'tools:setEnabled',
    'tools:setChatCursorBaselineEnabled',
    'tools:setChatToolSliceEnabled',
    'tools:setChatWorkspaceLedgerEnabled',
    'performance:settings',
    'performance:update',
    'performance:summary',
    'performance:paint',
    'trace:setActive',
    'trace:snapshot',
    'trace:clear',
    'models:manifest',
    'models:setEnabled',
    'models:setEnabledMany'
  ]
  assert.equal(channels.size, typed.length)
  for (const channel of typed) assert.ok(channels.has(channel), channel)
})

test('IPC sync constants cover the typed sync registry', () => {
  const channels = new Set(leafValues(IPC.sync))
  const typed: IpcSyncChannel[] = ['profiles:bootstrap', 'profiles:write']
  assert.equal(channels.size, typed.length)
  for (const channel of typed) assert.ok(channels.has(channel), channel)
})

test('IPC event constants cover the typed event registry', () => {
  const channels = new Set(Object.values(IPC.event))
  const typed: IpcEventChannel[] = [
    'browser:state',
    'browser:tabs',
    'browser:permissionRequests',
    'browserDownloads:changed',
    'savedSites:changed',
    'notes:changed',
    'chat:event',
    'agentRuns:event',
    'agentLibrary:changed',
    'security:credentialApprovals',
    'tools:event',
    'performance:settingsChanged',
    'trace:event',
    'models:event',
    'windows:event'
  ]
  assert.equal(channels.size, typed.length)
  for (const channel of typed) assert.ok(channels.has(channel), channel)
})
