// The stable control map of the ClosedAI renderer. Every interactive control carries a
// `data-ui` id from this list (and `data-ui-key`, surfaced to models as `item`, when it repeats per row, tab, or menu entry), so a
// model drives the real UI by id instead of discovering it from an accessibility dump. The
// guard test beside this file keeps the renderer source and this manifest in step.

export const UI_CONTROLS = {
  'file.copy-path': 'Copy the local file preview path',
  'file.copy-content': 'Copy the local file preview text',
  'file.reveal': 'Reveal the previewed local file in the system file manager',
  'file.view': 'Local HTML or SVG tab: switch the same tab between the rendered page and its source; item is page or code',
  'titlebar.chat-search': 'Search chats in the chat header (centred on cards): same flat history list and matcher as Manage chat history; type to filter titles, previews, and project folders. Escape, opening a result, a click outside, or focus leaving hides suggestions',
  'titlebar.chat-search-clear': 'Clear chat search',
  'titlebar.chat-search-result': 'Open a chat from header search; item is the chat id',
  'titlebar.chat-search-more': 'Show the next page of header search results',
  'titlebar.chat-search-delete': 'Archive a chat from header search immediately without confirmation; item is the chat id',
  'titlebar.fit-hit': 'Application title bar (File/View/Agent/Developer row): double-click the open band before minimize/maximize/close to fit and cycle visible desk windows—not the per-chat Search threads header',
  'titlebar.menu': 'Application menu tab; item is file, view, agent, or developer',
  'titlebar.menu-item': 'Application menu row; item is its stable key, for example new-chat, sign-out, tools, compact-context, stop-turn, turn-trace, reload-renderer, toggle-devtools; closedai_app.menu runs the same row by key in one call without opening the menu',
  'window.minimize': 'Minimize the window',
  'window.maximize': 'Maximize or restore the window',
  'window.close': 'Close the window',

  'layout.browser-dock': 'Drop a chat tab or pane on the left or right half to place it beside the browser',
  'layout.browser-drag': 'Browser window grip: drag to move the browser window; drop at a workspace side or a chat edge to tile it, anywhere else to float it',
  'layout.pane-drag': 'Chat window header grip (the header\u2019s empty space works too): drag to move the window; drop at a workspace side for a full-height column (half the workspace when nothing else is tiled; beside a window already filling the other half, the two tile as a pair), the top edge to maximize, a window\u2019s tab strip to join its tabs, a tiled window\u2019s outer band to split beside it, anywhere else to float it (tearing a window out of the tiled layout leaves the others floating where they were); double-clicking a floating window\u2019s header puts it back into its slot; item is the active chat id',
  'layout.window-minimize': 'Window header button: minimize the window to the dock (the browser hides); disabled for the last visible chat; item is the active tab id, or browser',
  'layout.window-maximize': 'Window header button: solo maximize this window (hide others) or restore; double-click the header solo-maximizes when only one window is open, otherwise cycles desk layouts; item is the active tab id, or browser',
  'layout.window-resize': 'Floating window edge or corner grip: drag to resize; item is the edge (n, s, e, w, ne, nw, se, sw)',
  'layout.keep-on-top': 'Chat window context menu checkbox: keep this whole window, every tab in it, above windows without it; the browser gives way to it rather than going under; item is the active tab id',
  'layout.menu-window': 'Chat window context menu: open the Window submenu (close, dismiss, move tab, detach); item is the active tab id',
  'layout.menu-chat': 'Chat window context menu: open the Chat submenu (layout, rename, pin, pause/resume); item is the chat pane id',
  'layout.tools-preset': 'Pane header label present only while the tools registry is in the Read-only preset; no item',
  'layout.card-new-chat': 'Chat card header +: start a new chat in its own window; halves the roomiest tile when the desk is full, otherwise floats beside the current chat; item is the card\u2019s pane id',
  'layout.card-continue': 'Chat card header: continue the full conversation in a new chat card with a fresh context window; disabled while the chat is running or empty; item is the card\u2019s pane id',
  'layout.new-chat': 'Notepad tab strip +: add and select a new note tab; item is the tile\u2019s active tab id',
  'layout.tab': 'Select a conversation or view tab, or drag it to a tile header to join its tabs, a pane edge to split it out, or free space (a floating window\u2019s body included) to open it in its own floating window there; item is the chat id or view tab id',
  'layout.tab-close': 'Remove a conversation or view tab from this tile without deleting history or stopping its turn; item is the chat id or view tab id',
  'layout.rename': 'Tab context menu: rename this chat; item is the chat id',
  'layout.pin': 'Tab context menu: pin or unpin this chat in history; item is the chat id',
  'layout.pause-tab': 'Tab context menu: pause the running task in this chat without opening it; item is the chat id',
  'layout.resume-tab': 'Tab context menu: resume a paused task in this chat; item is the chat id',
  'layout.card-pin': 'Chat card header star: swap a side chat with the main chat in the persistent sidebar layout; elsewhere pin or unpin (aria-pressed reports pinned); item is the chat id',
  'chat.zoom-in': 'Chat context menu: zoom in (same as View → Zoom in); item is the chat pane id',
  'chat.zoom-out': 'Chat context menu: zoom out; item is the chat pane id',
  'chat.reset-zoom': 'Chat context menu: reset chat zoom to 100%; item is the chat pane id',
  'chat.copy': 'Chat context menu: copy the current text selection; item is the chat pane id',
  'chat.paste': 'Chat context menu: paste clipboard text into the composer; item is the chat pane id',
  'layout.pane-hide': 'Window close button or header context menu: for a chat card, remove the card from the workspace and keep the conversation in history without stopping its turn; for other windows, close the window; item is the chat id',
  'layout.presets': 'Header context-menu row (also View → Workspace layout): open the workspace layout dialog; item is the chat id',
  'layout.presets-dialog': 'Workspace layout dialog: pick a starting arrangement that saves like any hand-built layout',
  'layout.preset-browser-centre': 'Layout dialog option: browser in the centre with two stacked chats on each side',
  'layout.preset-grid': 'Layout dialog option: browser hidden, chats in a balanced grid sized for the window',
  'layout.preset-grid-count': 'Layout dialog number input: how many chats the grid option arranges, clamped to what the window fits (at most 12)',
  'layout.preset-grid-decrement': 'Layout dialog: one fewer chat in the grid option',
  'layout.preset-grid-increment': 'Layout dialog: one more chat in the grid option',
  'layout.preset-apply': 'Layout dialog: apply the selected arrangement; open tiles keep their tabs, missing slots get new chats',
  'layout.preset-cancel': 'Layout dialog: close without changing the layout',
  'layout.preset-menu-custom': 'View → Workspace layout…: open the full workspace layout dialog with custom grid count',
  'layout.dock-preset': 'View menu preset: apply one of five full-workspace starting arrangements without opening the layout dialog; item is browser-side, browser-between, browser-centre, six or four; every open window and tab, floating or minimized, lands in the preset\u2019s windows',
  'layout.side-scroll': 'Scrollable side chats beside the persistent main chat; wheel, scrollbar, or keyboard scroll; item is the sidebar split id',
  'layout.divider': 'Resize adjacent chat or browser tiles by dragging the gutter or using arrow keys (Shift for fine control); double-click balances, Escape cancels a drag; item is the split id',
  'layout.tab-move': 'Tab context menu: move the active conversation into the next or previous tile in reading order; item is next or previous',
  'layout.tab-detach': 'Tab context menu: move this tab into a new window that can be placed on another monitor; item is the tab id',
  'layout.tab-return': 'Tab context menu in a detached window: move this tab back into the main window; item is the tab id',
  'spaces.slot': 'Workspace overview (View → Workspace overview, Ctrl+Shift+O, or Ctrl+scroll out): zoom into this workspace, switching to its project; item is the project folder',
  'spaces.add': 'Workspace overview: the Add workspace tile; adds a workspace in the current folder with a fresh chat left of the browser and zooms into it',
  'spaces.close': 'Workspace overview: close this workspace, preserving chats and files; switches to a neighbour if current; disabled for the last workspace; item is the space id',
  'dock.library': 'Open the workspace surface library; launch surfaces or pin them to the footer',
  'dock.library-app': 'Open a surface from Library; item is the tray app id',
  'dock.library-pin': 'Pin or unpin a surface on the footer; item is the tray app id',
  'dock.tools': 'Open Tools and capabilities from Library',
  'dock.bar': 'Hover-reveal footer dock; hover the dock control cluster to show it, right-click its backing for Add to dock',
  'files.refresh': 'Refresh the working directory file tree',
  'files.collapse': 'Collapse all folders in the file tree',
  'files.close': 'Hide the file tree; the Files dock icon restores it',
  'files.entry': 'Expand a folder or open a file in the built-in viewer; item is its path',
  'dock.pinned': 'Pinned dock icon: open or focus a workspace surface; right-click to unpin; item is the tray app id',
  'dock.unpin': 'Dock icon context menu: unpin this shortcut without closing its surface; item is the icon id',
  'dock.add-menu': 'Dock context menu: expand Add to dock to restore an unpinned shortcut',
  'dock.pin': 'Add to dock submenu: pin a shortcut; item is the icon id',
  'dock.overview': 'Footer Workspaces button: open the workspace overview or return to the current workspace',
  'dock.download': 'Library Downloads list: show a finished file in its folder; item is the download id',
  'dock.window': 'Dock tile for a minimized window: restore it where it was and select it; item is the window\u2019s front tab id',
  'dock.usage': 'Dock: open the subscription usage flyout above the footer rail listing every provider plan; the button shows the lowest remaining percent across plans',
  'dock.usage-refresh': 'Usage flyout: request a fresh reading of every provider plan',
  'dock.usage-retry': 'Usage flyout plan without a reading: read that provider again; item is the provider/account key',
  'dock.settings': 'Open application settings from the footer',


  'chat.rename-dialog': 'Dialog for renaming a chat conversation',
  'chat.rename-input': 'Input for custom chat title',
  'chat.rename-save': 'Save custom chat title',
  'chat.rename-reset': 'Reset chat title to default',
  'chat.rename-cancel': 'Cancel renaming chat',
  'chat.message-copy': 'Copy an assistant response; item is the message id',
  'chat.local-file': 'Open a local image in a browser-pane image tab or reveal another local file; item is the file link',
  'chat.generated-image': 'Open a generated image at full size in a browser-pane image tab; item is the transcript image id',
  'chat.message-branch': 'Branch in a new chat through this response; digest and recall stop at this message; item is the message id',
  'chat.background-group': 'Expand or collapse background work; item is the first task id',
  'chat.background-task': 'Expand task description and result; item is the task id',
  'chat.history': 'Chat history list inside a History view tab (present only while one is open)',
  'chat.show-earlier': 'Load one earlier user/model turn while keeping loaded chat history visible',
  'chat.history-search': 'Filter the chat history list',
  'chat.history-open': 'Open a thread from history; item is the thread id',
  'chat.history-archive': 'Archive a thread from history immediately; item is the thread id',
  'chat.history-retry': 'Retry loading chat history',
  'chat.history-more': 'Show the next page of older chats in the History view list (50 per page)',
  'chat.sign-in': 'Sign in with ChatGPT when the pane is signed out',
  'chat.choose-model': 'Open the model menu from an unavailable or signed-out empty state or connection banner',
  'chat.notice-dismiss': 'Dismiss the pane-level notice shown after a failed pane action',
  'chat.credential-allow': 'Approval card (Settings → Security, off by default): let the agent read the requested credential fields; item is the request id',
  'chat.credential-deny': 'Approval card (Settings → Security, off by default): refuse the credential request; item is the request id',
  'chat.agent-pause': 'Agent strip above the composer: stop driving this chat and end the turn in flight; the run keeps its cycle count',
  'chat.agent-resume': 'Agent strip above the composer: drive the paused agent again, at once when the pane is idle',
  'chat.agent-stop': 'Agent strip above the composer: end the agent run; the chat stays open as an ordinary chat',
  'shell.startup-retry': 'Retry the initial chat workspace snapshot after a failed start',
  'shell.error-reload': 'Reload the renderer from the error panel after a render failure',
  'shell.alert-dismiss': 'Dismiss the shell-level alert shown after a failed shortcut or menu action',

  'onboarding.gate-sign-in': 'Session gate: choose a local profile to unlock; item is the profile id',
  'onboarding.gate-back': 'Session gate: return from password or create account to the profile list',
  'onboarding.gate-create-start': 'Session gate: open create-account when the profile is not listed',
  'onboarding.gate-display-name': 'Session gate: username for a new local profile',
  'onboarding.gate-password': 'Session gate: password for the selected profile',
  'onboarding.gate-new-password': 'Session gate: password when creating a new local profile',
  'onboarding.gate-confirm-password': 'Session gate: confirm password; item distinguishes fields when both exist',
  'onboarding.gate-password-peek': 'Session gate: show or hide a password field; item is the input id',
  'onboarding.gate-password-submit': 'Session gate: submit the password for the selected profile',
  'onboarding.gate-create': 'Session gate: create a new local profile and continue',
  'onboarding.gate-keep-signed-in': 'Session gate: keep this profile signed in on the next launch',
  'onboarding.gate-delete-start': 'Session gate: open the delete-account step for the selected profile; item is the profile id',
  'onboarding.gate-delete-confirm': 'Session gate: delete the profile and move its workspace data to the trash; item is the profile id',
  'dialog.onboarding-providers': 'First-run dialog: connect chat providers before using the workspace',
  'onboarding.provider-sign-in': 'Provider setup: open sign-in for a provider; item is codex, claude, antigravity, or cursor',
  'onboarding.provider-disconnect': 'Provider setup: clear a provider marked connected during onboarding; item is the provider id',
  'onboarding.provider-refresh': 'Provider setup: re-check which provider binaries are installed',
  'onboarding.provider-skip': 'Provider setup: continue without connecting a provider',
  'onboarding.provider-continue': 'Provider setup: finish onboarding after at least one provider is connected',

  'diff.toggle-view': 'Toggle between unified and side-by-side split diff view; item is unified or split',
  'diff.collapse-all': 'Collapse or expand all hunks in the diff viewer',
  'diff.collapse-hunk': 'Collapse or expand a specific diff hunk; item is the hunk index',
  'diff.copy-hunk': 'Copy an individual diff hunk to clipboard; item is the hunk index',

  'composer.input': 'Message textarea of the selected pane; Enter or the send button sends, Shift+Enter inserts a newline',
  'composer.send': 'Send the draft (present while no turn runs; disabled until there is text or an attachment)',
  'composer.setup': 'Open the model setup panel — model, reasoning effort, and context/plan usage (model half of the capsule setup chip)',
  'composer.model-provider': 'Open the models of a provider in a flyout beside the setup panel; item is the provider id',
  'composer.model-item': 'Choose a model in the provider flyout of the setup panel; item is the model id',
  'composer.context': 'Expand the context and plan usage line at the top of the setup panel',
  'composer.effort-item': 'Choose a reasoning effort in the setup panel; item is the effort',
  'chat.folder-choose': 'Working folder for this chat pane: opens the folder picker; the name is the directory agents should use for repo work (see app checkout in runtime for the host app)',
  'composer.project-new': 'Choose a working folder for this chat from the folder panel, preserving the layout',
  'composer.project-recent': 'Change this chat to a previously used folder; item is its folder path',
  'composer.project-clear': 'Use the home directory for this chat',
  'composer.usage': 'Context window and plan usage block in the setup panel',
  'composer.compact': 'Compact provider-side context from a transcript summary (setup panel)',
  'composer.more': 'Toggle the composer + speed dial, revealing new chat, fresh context, and attachment actions to the right',
  'composer.upload': 'Attach files from the paperclip in the composer + speed dial',
  'composer.attachment-remove': 'Remove a pending attachment; item is the attachment id',
  'composer.attachment-preview': 'Open an attached image in a browser-pane image tab; item is the attachment id',
  'composer.stop': 'Pause the running turn via button or Escape key (present only while running)',
  'composer.resume': 'Resume the turn the pause button ended (present only while a turn is paused)',
  'composer.agents': 'Open this chat pane\u2019s saved-agent menu from the capsule\u2019s agents icon: pick a built agent to start, create a new one, or open Manage; item is the pane id',
  'composer.agents-start': 'Start a new run for a saved agent beside this chat\u2019s tile, or focus its tab when that run is already live; item is the saved agent id',
  'composer.agents-new': 'Open the Agents view on the New agent builder',
  'composer.agents-manage': 'Open or focus the workspace Agents view tab (Library, Build, Runs)',

  'browser.tab': 'Select a browser tab; item is the tab id',
  'browser.notice-dismiss': 'Dismiss the browser chrome notice reporting a rejected tab or navigation command',
  'browser.permission-allow': 'Permission bar (Settings → Security set to Ask): grant the active page its camera, microphone, screen, location, or notification request; item is the request id',
  'browser.permission-block': 'Permission bar (Settings → Security set to Ask): refuse the active page’s request; item is the request id',
  'browser.tab-close': 'Close a browser tab; item is the tab id',
  'browser.tab-menu': 'Right-click context menu for a browser tab',
  'browser.tab-menu-item': 'Browser tab context menu item; item is new-right, reload, duplicate, rename, save-site (saves or unsaves the tab’s page), close, close-others, or close-right',
  'browser.tab-rename': 'Inline browser tab rename field; item is the tab id',
  'browser.tab-new': 'Open a new browser tab',
  'browser.back': 'Browser back',
  'browser.forward': 'Browser forward',
  'browser.reload': 'Browser reload',
  'browser.suggestion': 'Navigate to an address suggestion; item is its URL',
  'browser.suggestion-remove': 'Remove a saved browser history entry; item is its URL',
  'browser.address': 'Address bar',
  'browser.downloads': 'Show or hide the downloads shelf',
  'quick-chat.compact': 'Notepad chat header: shrink to the status line over the composer so the note shows; item is notepad',
  'quick-chat.menu': 'Notepad chat header: more actions (Clear chat); item is notepad',
  'quick-chat.new': 'Notepad chat menu: Clear chat, starting a fresh chat for this notepad window; the previous one stays in chat history (disabled while a task runs); item is notepad',
  'quick-chat.expand': 'Compact notepad chat, on its status line: show the whole chat; item is notepad',
  'quick-chat.close': 'Notepad chat header or status line: hide the chat to its round button (Ctrl+J; Esc from inside the card); item is notepad',
  'browser.saved-sites': 'Star left of Downloads: save or unsave the active web page (gold when saved). Disabled on non-web pages',

  'saved-sites.open': 'Navigate the active tab to a saved site; item is the saved-site id',
  'saved-sites.log': 'Brief check log for a saved site (last check time and summary); item is the saved-site id',
  'saved-sites.note-edit': 'Open the optional note on a saved site for editing (shows the note text, or "Add note" when empty); item is the saved-site id',
  'saved-sites.note': 'Note field shown after saved-sites.note-edit; Enter or blur saves, Escape reverts; item is the saved-site id',
  'saved-sites.remove': 'Remove a saved site; item is the saved-site id',

  'downloads.clear': 'Clear finished downloads',
  'downloads.hide': 'Hide the downloads shelf',
  'downloads.pause': 'Pause a download; item is the download id',
  'downloads.resume': 'Resume a download; item is the download id',
  'downloads.reveal': 'Show a download in its folder; item is the download id',
  'downloads.cancel': 'Cancel a download; item is the download id',

  'view.tools': 'Tools & capabilities view tab body, opened through the tile + menu or Agent → Tools & capabilities; item is the view tab id',
  'view.trace': 'Turn trace view tab body for the chat the view follows or is pinned to, opened through the tile + menu or Developer → Turn trace; item is the view tab id',
  'view.agents': 'Agents dialog: a modal (never a tab) with a Library of saved-agent cards and pushed Build and Runs screens; runs dock beside the chat it was opened from. Opened from the composer agents menu, the dock or Agent → Agents…',
  'view.history': 'History view tab body listing chats across directories a page at a time (the same rows, order, and matcher as header search; chat.history-more pages older chats), opened through the tile + menu or File → Manage chat history; item is the view tab id',
  'view.saved-sites': 'Saved sites view tab: kept pages with notes and brief check log (lastCheckedAt and lastSummary), opened through the tile + menu or Developer → Saved sites; item is the view tab id',
  'view.file': 'File view tab body: a local text file (or its diff) opened from the file tree, a chat file link or a diff card, shown in the selected chat\u2019s tile instead of a browser tab; item is the view tab id (closedai:view:file:<encoded path>)',
  'view.note': 'Notepad window body for one note tab (a tile whose tabs are notes): the editor, the status line, and the window\u2019s chat button or card over the notes; item is the view tab id (closedai:view:note:<noteId>)',
  'notepad.editor': 'The note\u2019s text editor (CodeMirror: line numbers, Ctrl+F search, undo); lines a model wrote are marked in the gutter until the next task; item is the note id',
  'notepad.chat': 'Round button in the notepad window\u2019s bottom-right corner: open the window\u2019s one chat, about the note in front (created on first open; Ctrl+J while typing in the note). While its task runs it carries a progress ring and the note\u2019s title',
  'notepad.chat-go-to-task': 'Shown while the window\u2019s task runs on another tab: switch to the note the task is editing',
  'notepad.caret': 'Notepad status line: caret line and column (and the selection size)',
  'notepad.new': 'Notepad status line: new empty note as a tab in this window (an empty note is dropped when its tab closes)',
  'notepad.notes': 'Notepad status line: menu of notes not open in this window, and Delete this note',
  'notepad.open-note': 'Notes menu: open this note as a tab in this window; item is the note id',
  'notepad.delete': 'Notes menu: delete the note in front for good; its tab closes',
  'view.scope': 'Scope chip in a view toolbar (Trace, Tools, History; Agents and Saved sites have none): Following (the tile\u2019s own chat, dashed) or Pinned (one chat, solid); opens the scope menu; item is the view tab id',
  'view.scope-follow': 'Scope menu: return the view to following its tile; item is the view tab id',
  'view.scope-pin': 'Scope menu: pin the view to one open chat so moving it never retargets; item is the chat id',
  'dialog.settings': 'Settings dialog root with Appearance, Models, Performance, Credentials, and Security tabs, opened through File → Settings (present only while open)',
  'agents.new': 'Open the Build screen on a blank draft (Library header, or the empty Library and empty Runs states)',
  'agents.card': 'A saved agent card on the Library screen: name, the first lines of its description (or of its instructions when it has none), and its use line with its limits or its live run\u2019s state, cycle and time left; item is the agent id',
  'agents.edit': 'Open a saved agent in the Build screen; item is the agent id',
  'agents.card-start': 'Start a run from a saved agent card and stay on the Library; item is the agent id',
  'agents.runs': 'Open the Runs screen; the label carries the run summary (running, needs you, paused) when any run exists',
  'agents.back': 'Return from the Build or Runs screen to the Library; an unsaved Build draft is kept for the session',
  'agents.name': 'Agent name in the editor; a named editor is saved when started, a blank one runs once and is not kept',
  'agents.description': 'Build screen: what the agent should do, in the user\u2019s own words; saved with the agent and the input to Optimize',
  'agents.suggestion': 'Build screen, shown while the description is empty: an agent idea; clicking it fills the description and starts nothing; item is the idea id',
  'agents.suggestions-shuffle': 'Build screen: deal a different set of agent ideas',
  'agents.optimize': 'Build screen: ask the launching chat\u2019s model to turn the description into standing instructions (takes a minute or two); hand-edited instructions are not replaced, the result waits as a proposal',
  'agents.optimize-cancel': 'Build screen, while Optimize runs: abandon the request; every field stays as it was',
  'agents.optimize-undo': 'Build screen: bring back the instructions the last Optimize replaced',
  'agents.proposal-view': 'Build screen, while a proposed version waits: show the new version or the user\u2019s current instructions; item is proposed or current',
  'agents.proposal-text': 'Build screen: the proposed instructions, read-only until accepted',
  'agents.proposal-accept': 'Build screen: replace the instructions with the proposed version; the replaced text stays available through Undo optimize',
  'agents.proposal-dismiss': 'Build screen: discard the proposed version and keep the current instructions',
  'agents.assumptions': 'Build screen: what Optimize assumed where the description was silent, listed under the instructions',
  'agents.max-cycles': 'Cycle limit in the editor; blank runs until paused',
  'agents.time-limit': 'Build screen: switch a running-time limit on or off; when the time is used main pauses the run as its turn in flight ends and sends no further cycle, and paused time is not counted',
  'agents.time-amount': 'Build screen: the time limit amount, shown while the time limit is on',
  'agents.time-unit': 'Build screen: the time limit unit; item is minutes or hours',
  'agents.apply-suggested-limits': 'Build screen, after Optimize suggested limits that differ from the fields: write the suggested cycle and time limits into them',
  'agents.autonomy': 'Build screen: on sends the next cycle as soon as a turn ends; off makes the run supervised, paused by main after every cycle until resumed',
  'agents.prompt': 'Standing instructions in the editor, typed directly or written by Optimize; sent as cycle 1 in a new chat and again after a context rotation',
  'agents.save': 'Save the editor as a new agent or update the loaded one (enabled while named and changed)',
  'agents.start': 'Start an agent run in a new chat from the Build screen, saving a named agent first, then return to the Library; main re-sends a cycle after every finished turn until paused',
  'agents.delete': 'Delete the saved agent open in the Build screen and return to the Library; the first click asks for confirmation',
  'agents.run': 'An agent run row in the Agents tab runs table with state, cycle, time left under a time limit, and current activity, followed by a brief row of sentences on progress and time, the last reply, per-cycle context cost and plan windows, and errors; item is the chat id',
  'agents.open-chat': 'Open an agent run\u2019s chat in the workspace; item is the chat id',
  'agents.review': 'Open an agent run\u2019s chat to answer its pending credential approval; item is the chat id',
  'agents.pause': 'Pause a running agent run after its current turn; item is the chat id',
  'agents.resume': 'Resume a paused agent run, or send a supervised run its next cycle; item is the chat id',
  'agents.stop': 'Stop an agent run, or Dismiss a finished one; its card leaves the Agents tab and the chat is kept; item is the chat id',
  'dialog.performance': 'Performance settings and response timing summary',
  'settings.instant-streaming': 'Show response text immediately without pacing',
  'settings.provider-warm-time': 'Choose the provider idle warm-time in minutes',
  'settings.provider-warm-chats': 'Choose how many idle background chats remain warm',
  'settings.auto-titles': 'Enable or disable automatic chat title requests',
  'settings.tab': 'Switch the Settings dialog section; item is appearance, models, performance, credentials, or security',
  'dialog.models': 'Models section of Settings: choose which provider models appear in the composer menu',
  'settings.models-provider': 'Select a connected provider in Settings → Models; item is the provider id',
  'settings.models-toggle': 'Show or hide a model in the composer menu; item is the model id',
  'dialog.credentials': 'Credential vault panel inside the Settings dialog (present only while its tab is shown)',
  'dialog.security': 'Security panel inside the Settings dialog (present only while its tab is shown)',
  'security.credentials-approval': 'Switch: ask the user in the chat before an agent reads a saved credential’s secret fields',
  'security.secrets-keychain': 'Switch: refuse to save a secret when the OS keychain cannot encrypt it',
  'security.web-permissions': 'Choose what a website gets when it asks for camera, microphone, screen, or location; item is allow, ask, or block',
  'security.import-cookies': 'Switch: import signed-in sites from the default Chromium-family browser on launch',
  'security.import-now': 'Import browser cookies now and show the result beside the button',
  'image.zoom-in': 'Zoom into the active image tab',
  'image.zoom-out': 'Zoom out of the active image tab',
  'image.fit': 'Fit the active image to the browser pane',
  'image.actual-size': 'Display the active image at actual size',
  'image.download': 'Download the active image',
  'image.reveal': 'Reveal the active image file in the file manager',
  'image.canvas': 'Image viewport; drag to pan or use +, -, 0 (fit), and 1 (actual size)',
  'video.reveal': 'Reveal the active video file in the file manager',
  'video.fullscreen': 'Fullscreen the active video in the browser pane',
  'video.stage': 'Video viewport; space to play or pause, arrow keys to seek, m to mute, f for fullscreen',
  'video.skip-back': 'Seek back ten seconds in the active video',
  'video.home-search': 'Search videos in Downloads and the Videos folder',
  'video.home-open': 'Open a video file from disk',
  'video.home-open-item': 'Open a listed video; item is the absolute file path',
  'video.play': 'Play or pause the active video',
  'video.skip-forward': 'Seek forward ten seconds in the active video',
  'video.mute': 'Mute or unmute the active video',
  'video.loop': 'Toggle loop playback for the active video',
  'video.compare-sync': 'Toggle synced playback in video compare mode',
  'video.compare-clear': 'Exit side-by-side video compare',
  'video.compare-audio': 'Choose which compared video plays audio; item is the tab id',
  'dialog.close': 'Close the open dialog',
  'tools.clear': 'Reset tool usage counts',
  'tools.toggle': 'Turn a tool on or off (every verb of an action tool); item is the tool id',
  'tools.group-toggle': 'Turn a whole effect group on or off; item is reads-web, acts-in-browser, controls-app, reads-secrets, or runs-native',
  'tools.group-select': 'Select an effect group in the Tools view rail; item is reads-web, acts-in-browser, controls-app, reads-secrets, or runs-native',
  'tools.row': 'Open or close a tool row\u2019s details; item is the tool id',
  'tools.schema': 'Show or hide the advertised schema inside an open tool overview; item is the tool id',
  'tools.preset': 'Apply a preset to every switch; item is full or read-only (custom is the detected state, not a button)',
  'tools.suggest-off': 'Turn off a tool the view suggests is unused and costly; item is the tool id',
  'tools.suggestions-apply': 'Turn off every suggested tool at once',
  'tools.cursor-baseline': 'Use Cursor baseline policy for Codex, Claude, and Antigravity',
  'tools.task-slice': 'Turn Codex task-based tool slices on or off (which tools load eagerly each turn)',
  'tools.workspace-ledger': 'Turn host-verified workspace ledger context on or off for coding sends',
  'tools.repair': 'Put a repair request with the tool\u2019s recent failure messages into the composer of the chat the Tools view follows, bringing that chat forward; item is the tool id',
  'trace.refresh': 'Refresh the turn trace',
  'trace.clear': 'Clear the turn trace',
  'trace.filter': 'Toggle a trace filter; item is the entry kind or all-panes',
  'credentials.add': 'Open the create-credential form',
  'credentials.undo-remove': 'Restore a credential during its removal undo window; item is its id',
  'credentials.detect': 'Service URL or name that selects the service and its logo',
  'credentials.service': 'Choose which service the credential is for; item is the service id',
  'credentials.docs': 'Open the page where the selected service issues the credential',
  'credentials.label': 'Name the vault entry',
  'credentials.field': 'Credential value input; item is <serviceId>.<fieldId>',
  'credentials.peek': 'Show or hide a secret while typing it; item is <serviceId>.<fieldId>',
  'credentials.save': 'Validate and write the credential to the encrypted vault',
  'credentials.cancel': 'Leave the create form and return to the vault list',
  'credentials.reveal': 'Decrypt and show a stored secret; item is <credentialId>.<fieldId>',
  'credentials.copy': 'Copy a stored secret to the clipboard; item is <credentialId>.<fieldId>',
  'credentials.delete': 'Delete a stored credential; item is the credential id',
  'credentials.agent-access': 'Switch whether agents may read a stored credential through the credential_vault tools; item is the credential id',
  'settings.reset': 'Reset appearance settings',
  'settings.wallpaper': 'Open the workspace wallpaper picker from Settings → Appearance (closes Settings)',
  'workspace.backdrop': 'Change the workspace background from empty canvas space; item is off, desktop, or a preset id',
  'workspace.wallpaper': 'Open the workspace wallpaper picker from the empty-canvas background menu; item is open',
  'dialog.wallpaper': 'Workspace wallpaper picker: current wallpaper, Curated presets and Your uploads; choices apply live (present only while open)',
  'wallpaper.mode': 'Wallpaper source in the picker; item is image (returns to the last picked image), desktop, or off',
  'wallpaper.select': 'Pick a wallpaper tile; item is the backdrop key, preset:<id> (aurora, dusk, ocean, ember) or upload:<uuid>',
  'wallpaper.add': 'Open the file chooser to add a JPEG, PNG, WebP or AVIF image to Your uploads; the added image becomes the wallpaper',
  'wallpaper.remove': 'Delete an uploaded wallpaper from this device; item is upload:<uuid>',
  'wallpaper.cancel': 'Close the wallpaper picker and restore the wallpaper it opened with',
  'wallpaper.done': 'Close the wallpaper picker keeping the current choice',
  'settings.decrease': 'Decrease an appearance value; item is chat-font-size, composer-font-size, or chat-zoom',
  'settings.range': 'Appearance slider; item is chat-font-size, composer-font-size, or chat-zoom',
  'settings.increase': 'Increase an appearance value; item is chat-font-size, composer-font-size, or chat-zoom'
} as const

export type UiControlId = keyof typeof UI_CONTROLS

export const UI_SURFACES = ['shell', 'chat', 'browser', 'browser-downloads', 'overlay'] as const

export type UiSurface = (typeof UI_SURFACES)[number]

/** Control families, for the tool description: the model learns the shape, not every id. */
export function uiControlFamilies(): string[] {
  return [...new Set(Object.keys(UI_CONTROLS).map((id) => id.slice(0, id.indexOf('.'))))]
}
