// The stable control map of the ClosedAI renderer. Every interactive control carries a
// `data-ui` id from this list (and `data-ui-key`, surfaced to models as `item`, when it repeats per row, tab, or menu entry), so a
// model drives the real UI by id instead of discovering it from an accessibility dump. The
// guard test beside this file keeps the renderer source and this manifest in step.

export const UI_CONTROLS = {
  'titlebar.drawer-toggle': 'Open or close the side drawer',
  'titlebar.menu': 'Application menu tab; item is file, edit, view, or help',
  'titlebar.menu-item': 'Application menu row; item is the slugged label, for example new-chat',
  'window.minimize': 'Minimize the window',
  'window.maximize': 'Maximize or restore the window',
  'window.close': 'Close the window',

  'layout.browser-toggle': 'Chat-header control to show or hide the shared browser independently of the chat arrangement; item is the chat id',
  'layout.browser-divider': 'Resize the chat area and shared browser',
  'layout.browser-dock': 'Drop a chat tab or pane on the left or right half to place it beside the browser',
  'layout.pane-drag': 'Focus a chat or drag its header to dock beside another; item is the chat id',
  'layout.new-chat-menu': 'Open the new-chat menu in a chat header (new tab, split right, split below); item is the chat id',
  'layout.new-chat': 'Menu row: add and select a fresh conversation tab in this tile, preserving its existing tabs, other tiles and split sizes; item is the active chat id',
  'layout.tab': 'Select a conversation tab, or drag it to a chat header to join its tabs or a pane edge to split out this conversation; item is the chat id',
  'layout.tab-close': 'Remove a conversation tab from this tile without deleting history or stopping its turn; item is the chat id',
  'layout.split-right': 'Menu row: create a chat to the right of this pane; item is the chat id',
  'layout.split-below': 'Menu row: create a chat below this pane; item is the chat id',
  'layout.pane-hide': 'Remove a tile from the layout without stopping its chat; item is the chat id',
  'layout.maximize': 'Context menu or double-click: maximize the chat tile to occupy the full canvas; item is the active chat id',
  'layout.restore': 'Context menu or Escape key: restore the split grid from maximized tile mode; item is the active chat id',
  'layout.divider': 'Resize adjacent chat or browser tiles with a drag or arrow keys; item is the split id',

  'drawer.new-agent': 'Start a new agent chat pane',
  'drawer.directory': 'Expand or collapse a directory section without changing projects; item is its full directory path',
  'drawer.directory-history': 'Expand or collapse chat history within a directory section; item is its full directory path',
  'drawer.search': 'Search previous chats (combobox)',
  'drawer.search-clear': 'Clear the drawer search',
  'drawer.search-result': 'Drawer search hit; item is the row id',
  'drawer.row': 'Open a pinned, running, review-queue, or history chat; item is the row id',
  'drawer.row-twisty': 'Show or hide the sub-agents of a row; item is the row id',
  'drawer.row-settled': 'Show or hide settled sub-agents; item is the row id',
  'drawer.row-stop': 'Stop a running agent row; item is the row id',
  'drawer.row-close': 'Close an open pane row, keeping its thread in History; item is the row id',
  'drawer.row-delete': 'Ask to delete a history row; item is the row id',
  'drawer.row-delete-confirm': 'Confirm deleting a row; item is the row id',
  'drawer.row-delete-cancel': 'Cancel deleting a row; item is the row id',
  'drawer.row-menu': 'Context menu of a drawer row (pin/unpin, split right/below, or continue in a new chat)',
  'drawer.row-split-right': 'Open or move this sidebar chat to the right of the focused pane; item is the chat id',
  'drawer.row-split-below': 'Open or move this sidebar chat below the focused pane; item is the chat id',
  'drawer.row-pin': 'Pin or unpin the chat in the row context menu; item is the chat id',
  'drawer.row-menu-item': 'Fork the row into a new chat; item is current or a model id',

  'chat.message-copy': 'Copy an assistant response; item is the message id',
  'chat.local-file': 'Open a local image in a browser-pane image tab or reveal another local file; item is the file link',
  'chat.message-branch': 'Continue in a new chat through this response; item is the message id',
  'chat.background-group': 'Expand or collapse background work; item is the first task id',
  'chat.background-task': 'Expand task description and result; item is the task id',
  'chat.background-jump': 'Open background task details above the chat',
  'chat.background-close': 'Close the background task details popup',
  'chat.history': 'Chat history panel (present only while open)',
  'chat.show-earlier': 'View or load one earlier user/model turn in the current chat',
  'chat.history-search': 'Filter the chat history list',
  'chat.history-open': 'Open a thread from history; item is the thread id',
  'chat.history-archive': 'Archive a thread from history; item is the thread id',
  'chat.history-retry': 'Retry loading chat history',
  'chat.sign-in': 'Sign in with ChatGPT when the pane is signed out',

  'composer.input': 'Message textarea of the selected pane',
  'composer.new-chat': 'Start a new chat from the composer',
  'composer.project': 'Open the active project menu',
  'composer.project-new': 'Choose a folder as a new project',
  'composer.project-recent': 'Switch to a previously used project; item is its folder path',
  'composer.project-clear': 'Leave project mode and use the home workspace',
  'composer.model': 'Open the model and reasoning-effort menu',
  'composer.model-provider': "Show a provider's models in the model menu; item is the provider",
  'composer.model-back': 'Return the model menu to the provider list; item is the provider being left',
  'composer.model-item': 'Choose a model; item is the model id',
  'composer.model-more': "Toggle a provider's model list between its top models and all of them; item is the provider",
  'composer.effort-item': 'Choose a reasoning effort; item is the effort',
  'composer.context': 'Open the context inspector',
  'composer.usage-card': 'Context window and plan usage, shown while the context meter is hovered',
  'composer.compact': 'Compact provider-side context from a transcript summary',
  'composer.compact-toggle': 'Toggle between compact progress pill and full composer',
  'composer.upload': 'Attach files',
  'composer.attachment-remove': 'Remove a pending attachment; item is the attachment id',
  'composer.attachment-preview': 'Open an attached image in a browser-pane image tab; item is the attachment id',
  'composer.stop': 'Pause the running turn (present only while running)',
  'composer.resume': 'Resume the turn the pause button ended (present only while a turn is paused)',
  'composer.send': 'Send the message (present only while idle)',

  'browser.tab': 'Select a browser tab; item is the tab id',
  'browser.tab-close': 'Close a browser tab; item is the tab id',
  'browser.tab-menu': 'Right-click context menu for a browser tab',
  'browser.tab-menu-item': 'Browser tab context menu item; item is new-right, reload, duplicate, rename, close, close-others, or close-right',
  'browser.tab-rename': 'Inline browser tab rename field; item is the tab id',
  'browser.tab-new': 'Open a new browser tab',
  'browser.back': 'Browser back',
  'browser.forward': 'Browser forward',
  'browser.reload': 'Browser reload',
  'browser.suggestion': 'Navigate to an address suggestion; item is its URL',
  'browser.suggestion-remove': 'Remove a saved browser history entry; item is its URL',
  'browser.address': 'Address bar',
  'browser.downloads': 'Show or hide the downloads shelf',

  'downloads.clear': 'Clear finished downloads',
  'downloads.hide': 'Hide the downloads shelf',
  'downloads.pause': 'Pause a download; item is the download id',
  'downloads.resume': 'Resume a download; item is the download id',
  'downloads.reveal': 'Show a download in its folder; item is the download id',
  'downloads.cancel': 'Cancel a download; item is the download id',

  'dialog.tools': 'Tools dialog root (present only while open)',
  'dialog.trace': 'Turn trace dialog root (present only while open)',
  'dialog.context': 'Context inspector dialog root (present only while open)',
  'dialog.settings': 'Appearance settings dialog root (present only while open)',
  'dialog.credentials': 'Credential vault dialog root (present only while open)',
  'image.zoom-in': 'Zoom into the active image tab',
  'image.zoom-out': 'Zoom out of the active image tab',
  'image.fit': 'Fit the active image to the browser pane',
  'image.actual-size': 'Display the active image at actual size',
  'image.download': 'Download the active image',
  'image.reveal': 'Reveal the active image file in the file manager',
  'image.canvas': 'Image viewport; drag to pan or use +, -, 0 (fit), and 1 (actual size)',
  'dialog.close': 'Close the open dialog',
  'tools.refresh': 'Refresh the tools list',
  'tools.clear': 'Clear tool usage counts',
  'tools.toggle': 'Turn a tool or action on or off; item is the tool id',
  'trace.refresh': 'Refresh the turn trace',
  'trace.clear': 'Clear the turn trace',
  'trace.filter': 'Toggle a trace filter; item is the entry kind or all-panes',
  'credentials.add': 'Open the create-credential form',
  'credentials.detect': 'Service URL or name that selects the service and its logo',
  'credentials.service': 'Choose which service the credential is for; item is the service id',
  'credentials.docs': 'Open the page where the selected service issues the credential',
  'credentials.label': 'Name the vault entry',
  'credentials.field': 'Credential value input; item is <serviceId>.<fieldId>',
  'credentials.peek': 'Show or hide a secret while typing it; item is <serviceId>.<fieldId>',
  'credentials.save': 'Validate and write the credential to the encrypted vault',
  'credentials.cancel': 'Leave the create form and return to the vault list',
  'credentials.reveal': 'Decrypt and show a stored secret; item is <credentialId>.<fieldId>',
  'credentials.copy': 'Copy a stored secret to the clipboard; item is <credentialId>.<fieldId>',
  'credentials.delete': 'Delete a stored credential; item is the credential id',
  'settings.reset': 'Reset appearance settings',
  'settings.decrease': 'Decrease an appearance value; item is chat-font-size, composer-font-size, or chat-zoom',
  'settings.range': 'Appearance slider; item is chat-font-size, composer-font-size, or chat-zoom',
  'settings.increase': 'Increase an appearance value; item is chat-font-size, composer-font-size, or chat-zoom'
} as const

export type UiControlId = keyof typeof UI_CONTROLS

export const UI_SURFACES = ['shell', 'side-drawer', 'chat', 'browser', 'browser-downloads', 'overlay'] as const

export type UiSurface = (typeof UI_SURFACES)[number]

/** Control families, for the tool description: the model learns the shape, not every id. */
export function uiControlFamilies(): string[] {
  return [...new Set(Object.keys(UI_CONTROLS).map((id) => id.slice(0, id.indexOf('.'))))]
}
