// Generates the repository index queried by the read-only workspace navigation tool.
// Run with --check in the completion gate and --write to refresh committed data.
import { readdir, readFile, stat, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const output = path.join(root, 'src/main/tools/workspace/workspace-index.generated.ts')
const indexedExtensions = new Set(['.css', '.html', '.js', '.json', '.md', '.mjs', '.ts', '.tsx'])
const ignoredDirectories = new Set(['coverage', 'dist', 'node_modules', 'out'])
const ignoredFiles = new Set(['package-lock.json', 'THIRD_PARTY_NOTICES.md'])
const maxModuleBytes = 45_000

function isTest(name) {
  return /\.test\.tsx?$/.test(name)
}

async function collectFiles(directory = root) {
  const files = []
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    if (entry.name.startsWith('.') || ignoredDirectories.has(entry.name)) continue
    const target = path.join(directory, entry.name)
    if (entry.isDirectory()) files.push(...await collectFiles(target))
    else if (
      entry.isFile() &&
      indexedExtensions.has(path.extname(entry.name)) &&
      !ignoredFiles.has(entry.name)
    ) {
      files.push(path.relative(root, target).replaceAll(path.sep, '/'))
    }
  }
  return files
}

// Match registration call sites only. A bare "a:b" literal is not evidence that a file
// owns an IPC namespace.
const handlerPattern = /ipcMain\s*\.\s*(?:handle|handleOnce|on|once)\(\s*['"]([a-zA-Z][a-zA-Z0-9]*):[a-zA-Z][a-zA-Z0-9]*['"]/g
const callerPattern = /ipcRenderer\s*\.\s*(?:invoke|send|on|once)\(\s*['"]([a-zA-Z][a-zA-Z0-9]*):[a-zA-Z][a-zA-Z0-9]*['"]/g

async function namespacesIn(relativePath, pattern) {
  const source = await readFile(path.join(root, relativePath), 'utf8')
  return new Set([...source.matchAll(pattern)].map(([, namespace]) => namespace))
}

async function mainIpcFiles() {
  const found = []
  const walk = async (directory) => {
    for (const entry of await readdir(directory, { withFileTypes: true })) {
      const target = path.join(directory, entry.name)
      if (entry.isDirectory()) await walk(target)
      else if (entry.isFile() && entry.name.endsWith('.ts') && !isTest(entry.name)) {
        const relativePath = path.relative(root, target).replaceAll(path.sep, '/')
        const namespaces = await namespacesIn(relativePath, handlerPattern)
        if (namespaces.size > 0) found.push({ file: relativePath, namespaces })
      }
    }
  }
  await walk(path.join(root, 'src/main'))
  return found
}

/** Maps each namespace exposed by preload to the main-process modules that handle it. */
async function ipcFlows() {
  const exposed = await namespacesIn('src/preload/index.ts', callerPattern)
  const handlers = await mainIpcFiles()
  return Object.fromEntries([...exposed].sort().flatMap((namespace) => {
    const owners = handlers
      .filter((handler) => handler.namespaces.has(namespace))
      .map((handler) => handler.file)
      .sort()
    return owners.length > 0 ? [[namespace, owners]] : []
  }))
}

const files = (await collectFiles()).sort()
const flows = await ipcFlows()
const module = `// GENERATED by scripts/repo-tree.mjs — do not edit. Run \`npm run map\` to refresh.
/** Absolute checkout described by this index. */
export const WORKSPACE_INDEX_ROOT = ${JSON.stringify(root)}

/** Navigable repository files. Test files remain data and are omitted only at query time. */
export const WORKSPACE_FILES = ${JSON.stringify(files)} as const

/** Preload IPC namespace -> main-process owner modules. */
export const WORKSPACE_IPC_FLOWS = ${JSON.stringify(flows)} as const
`

if (Buffer.byteLength(module) > maxModuleBytes) {
  console.error(`✗ workspace index is ${Buffer.byteLength(module)} bytes, above ${maxModuleBytes}`)
  process.exit(1)
}

const mode = process.argv[2] ?? '--write'
const current = await readFile(output, 'utf8').catch(() => null)

if (mode === '--check') {
  if (current === module) {
    console.log(`✓ workspace index current (${files.length} files, ${Object.keys(flows).length} IPC namespaces)`)
  } else {
    console.error('✗ workspace index is stale; run `npm run map`')
    process.exit(1)
  }
} else {
  if (current !== module) await writeFile(output, module)
  const bytes = (await stat(output)).size
  console.log(`workspace index: ${files.length} files, ${Object.keys(flows).length} IPC namespaces, ${bytes} bytes`)
}
